version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: blog_server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: blog_client
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://server:5000
